service: visma-serverless-course

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: api
  apiGateway:
    apiKeys:
      - testKey
  versionFunctions: false

frameworkVersion: "3"

functions:
  - hello:
      handler: handler.hello
      events:
        - http:
            path: /hello
            method: get
            private: true
  - calculate:
      handler: calculator.calculate
      events:
        - http:
            path: /calculate
            method: post
            private: true
